### ISSUE TITLE
UI issue on bottom left corner when updating feeds

### ISSUE THREAD

**Issue by rex4539** [brentsimmons/Evergreen#168]
Git @ 48ca636

![screen shot 2017-11-15 at 18 28 44](https://user-images.githubusercontent.com/227442/32847680-57ede890-ca33-11e7-8084-692436a6620c.png)

**Comment by brentsimmons** [comment]
Fixed in … well … earlier today.

**Comment by rex4539** [comment]
I still see it with Git @ Git @ 0e5b400

![screen shot 2017-11-16 at 09 14 06](https://user-images.githubusercontent.com/227442/32878462-b845c688-caae-11e7-94f2-11b2d128c959.png)

**Comment by brentsimmons** [comment]
Oooops. Done in 5150e7af95a449b6c822f473b0c85ea74872ab79.
